// Imports
//////////

// Import l10n + the translations &
// invoke the function using the translations.json file Generated by "npx l10n tables"
import L10n from "@tuicom/l10n/l10n"
import translations from "./l10n/translations.json";

export class Tui6mTutorialComponent extends HTMLElement {
    // Invoke the constructor
    constructor() {
        // Call the super constructor
        super();

        // Attach the shadow DOM
        this.shadow = this.attachShadow({mode: 'open'});

        // Initialize the translation creating a new instance of L10n & passing the
        // translations & the locale attribute of the custom component to its constructor
        this.l10n = new L10n(translations, this.getAttribute("locale"));
    }

    // Make the component aware of the locale attribute
    static get observedAttributes() {
        return ['locale']
    }

    // Invoked each time the custom element is appended into a document-connected element
    connectedCallback() {

        // Add the markup & styling to the shadow DOM
        this.shadow.innerHTML = `
            <!-- Styling -->
            <style>
                :host {
                    /* The "all" property resets any CSS inherited from the outer context */
                    all: initial;
                    display: block;
                    border: 5px solid #aaa;
                    background: #daffd5;
                    padding: 20px;
                }
            </style>
            
            <!-- HTML markup -->
            <div>
                ${this.l10n.t("Hello World")}
            </div>
        `
    }
}


// Define the custom element by providing a name to the class
// This name can now be used as a HTML tag in the index.html file where this js file is imported
customElements.define('tui-6m-tutorial-component', Tui6mTutorialComponent);